C NASA Ames RT code
C module defines_h
C #include DEFINES.h


      INTEGER L_LAYERP1,L_LAYERM1,L_LEVELM1,L_LEVELM2,L_LEVELM3
      INTEGER L_LEVELM4,L_NPDST

      PARAMETER(L_LAYERP1=L_LAYERS+1)
      PARAMETER(L_LAYERM1=L_LAYERS-1)
      PARAMETER(L_LEVELM1=L_LEVELS-1)
      PARAMETER(L_LEVELM2=L_LEVELS-2)
      PARAMETER(L_LEVELM3=L_LEVELS-3)
      PARAMETER(L_LEVELM4=L_LEVELS-4)
C     Number of fine-mesh layers used in calculating dust profiles
      PARAMETER(L_NPDST=100)

